// packages/vue/src/card.vue
<template>
  <div
    v-bind:class="[
      'ex-card',
    ]"
  >
    <img v-if="imgSrc" :src="imgSrc" class="ex-card_img" alt="image alt" />

    <div class="ex-card_body">
      <h4 class="ex-card_title" v-if="title">{{ title }}</h4>
      <h6 class="ex-card_subtitle" v-if="subtitle">{{ subtitle }}</h6>
      <div class="ex-card_content">
        <slot></slot>
      </div>
      <slot name="footer"></slot>
    </div>
  </div>
</template>

<script>
export default {
  props: {
    imgSrc: String,
    title: {
      type: String,
      required: true,
    },
    subtitle: {
      type: String,
      required: true,
    },
  },
};
</script>

// packages/react/src/card/card.tsx
import * as React from 'react';
import { CardProps } from '@knapsack-cloud/demo-design-system-shared-types';

export const Card: React.FC<CardProps> = ({
  title,
  subtitle,
  children,
  img
}) => {
  return (
    <div className="ex-card">
      {img && <img src={img} className="ex-card_img" alt="" />}
      <div className="ex-card_body">
        {title && <h4 className="ex-card_title">{ title }</h4>}
        {subtitle && <h6 className="ex-card_subtitle">{ subtitle }</h6>}
        {children &&
          <div>
            { children }
          </div>
        }
      </div>
    </div>
  );
};
