// packages/react/src/card/card.tsx
import * as React from 'react';
import { CardProps } from '@knapsack-cloud/demo-design-system-shared-types';

export const Card: React.FC<CardProps> = ({
  title,
  subtitle,
  children,
  img
}) => {
  return (
    <div className="ex-card">
      {img && <img src={img} className="ex-card_img" alt="" />}
      <div className="ex-card_body">
        {title && <h4 className="ex-card_title">{ title }</h4>}
        {subtitle && <h6 className="ex-card_subtitle">{ subtitle }</h6>}
        {children &&
          <div>
            { children }
          </div>
        }
      </div>
    </div>
  );
};

// packages/angular/src/lib/card/card.component.ts
import { Component, OnInit, ViewEncapsulation, Input } from '@angular/core';
@Component({
  selector: 'ap-ng-card',
  templateUrl: './card.component.html',
  encapsulation: ViewEncapsulation.None
})
export class CardComponent implements OnInit {
  @Input() 'img': string;
  @Input() 'title': string;
  @Input() 'subtitle': string;
  @Input() 'cardBody': string;
  constructor() {}

  ngOnInit(): void {}
}

<div class="ex-card">
  <img *ngIf="img" src="{{ img }}" class="ex-card_img" alt="">
  <div class="ex-card_body">
    <h4 *ngIf="title" class="ex-card_title">{{ title }}</h4>
    <h6 *ngIf="subtitle" class="ex-card_subtitle">{{ subtitle }}</h6>
    <div *ngIf="cardBody" [outerHTML]="cardBody"></div>
  </div>
</div>
