// packages/react/src/author/author.tsx
import * as React from 'react';
import cn from 'classnames';

export interface AuthorProps {
  date?: string;
  read?: string;
  imgSrc?: string;
  children?: React.ReactNode;
}

export const Author: React.FC<AuthorProps> = ({
  imgSrc,
  date,
  read,
  children
}: AuthorProps) => {
  const classes = cn(
    'flex',
    'items-center',
    'dark:bg-gray-900',
    'p-2'
  );
  return (
    <div className={classes}>
      <div className="flex-shrink-0">
        <a href="#">
          <span className="sr-only">{children}</span>
          {imgSrc && (
            <img className="h-10 w-10 rounded-full" src={imgSrc} alt="" />
          )}
        </a>
      </div>
      <div className="ml-3">
        <p className="text-sm font-medium text-gray-900 dark:text-white">
          <a href="#" className="hover:underline">
            {children}
          </a>
        </p>
        <div className="flex space-x-1 text-sm text-gray-500  dark:text-gray-400">
          {date && (
            <time dateTime="2020-03-10">
              {date}
            </time>
          )}
          {(date && read) && (
            <span aria-hidden="true">
              &middot;
            </span>
          )}
          {read && (
            <span>
              {read}
            </span>
          )}
        </div>
      </div>
    </div>
  )
};

export default Author;

// packages/vue/src/author.vue
<template>
  <div
    v-bind:class="[
      'flex',
      'items-center',
      'dark:bg-gray-900'
    ]"
  >
    <div v-if="imgSrc" class="flex-shrink-0">
      <a href="#">
        <span v-if="author" class="sr-only">{{ author }}</span>
        <img class="h-10 w-10 rounded-full" :src="imgSrc" alt="image alt" />
      </a>
    </div>
    <div class="ml-3">
      <p v-if="author" class="text-sm font-medium text-gray-900 dark:text-white">
        <a href="#" class="hover:underline">{{ author }}</a>
      </p>
      <div class="flex space-x-1 text-sm text-gray-500 dark:text-gray-400">
        <time v-if="date" datetime="2020-03-10">{{ date }}</time>
        <span v-if="date && read" aria-hidden="true">·</span>
        <span v-if="read">{{ read }}</span>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  props: {
    read: String,
    imgSrc: String,
    date: String,
    author: String,
  },
};
</script>
