// src/components/card/card.tsx
import * as React from 'react';
import cn from 'classnames';
import { CardProps } from '../../../dist/meta/react';

const Card: React.FC<CardProps> = ({
  children,
  cardBody,
  cardSubTitle,
  cardTitle,
  imgSrc,
}: CardProps) => {
  return (
    <div className="ex-card">
      {imgSrc && (
        <img
          className="ex-card_img"
          alt="An example image inside a card"
          src={imgSrc}
        />
      )}
      <div className="ex-card_body">
        <h5 className="ex-card_title">{cardTitle}</h5>
        {cardSubTitle && (
          <h6 className="ex-card_subtitle">{cardSubTitle}</h6>
        )}
        <p className="ex-card_text">{cardBody}</p>
        {children}
      </div>
    </div>
  );
};

export default Card;

// packages/vue/src/card.vue
<template>
  <div
    v-bind:class="[
      'ex-card',
    ]"
  >
    <img v-if="imgSrc" :src="imgSrc" class="ex-card_img" alt="image alt" />

    <div class="ex-card_body">
      <h4 class="ex-card_title" v-if="title">{{ title }}</h4>
      <h6 class="ex-card_subtitle" v-if="subtitle">{{ subtitle }}</h6>
      <div class="ex-card_content">
        <slot></slot>
      </div>
      <slot name="footer"></slot>
    </div>
  </div>
</template>

<script>
export default {
  props: {
    imgSrc: String,
    title: {
      type: String,
      required: true,
    },
    subtitle: {
      type: String,
      required: true,
    },
  },
};
</script>
